
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jrx
    username: root
    password: 123
server:
  port: 8080
logging:
  config: classpath:log4j2.yml
